import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/next"
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "400", "700", "900"]
});

export const metadata: Metadata = {
  title: "Shashanks Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/profilepic.png"
  }
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
        {children}
        <Analytics />
      </body>
    </html>
  );
}
